In [1]:
from simsopt.geo import CurveCWSFourier, SurfaceRZFourier, CurveRZFourier, RotatedCurve
import numpy as np  

In [2]:
order = 3

In [3]:
curve = CurveCWSFourier(mpol=1, ntor=1, idofs=[1, 0.2, 0.2], quadpoints=150, order=order, nfp=1, stellsym=True)

In [4]:
dofs = np.zeros((curve.dof_size, ))
print(dofs)
dofs[0] = 1.
dofs[2*order + 2] = 1.
print(dofs)
curve.x = dofs
print(curve.x)
# curve = RotatedCurve(curve, 0.5, flip=False)
print(curve.x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
cfc = curve
coeffs = cfc.x
cfc.invalidate_cache()

In [6]:
def taylor_test(f, df, x, epsilons=None, direction=None):
    np.random.seed(1)
    if direction is None:
        direction = np.random.rand(*(x.shape))-0.5
    dfx = df(x)@direction
    if epsilons is None:
        epsilons = np.power(2., -np.asarray(range(7, 20)))
    print("################################################################################")
    err_old = 1e9
    counter = 0
    for eps in epsilons:
        if counter > 8:
            break
        fpluseps = f(x + eps * direction)
        fminuseps = f(x - eps * direction)
        dfest = (fpluseps-fminuseps)/(2*eps)
        err = np.linalg.norm(dfest - dfx)
        print(err, err/err_old)
        
        assert err < 1e-9 or err < 0.3 * err_old
        if err < 1e-9:
            break
        err_old = err
        counter += 1
    if err > 1e-10:
        assert counter > 3
    print("################################################################################")

In [7]:
x = np.array([1. , 0.1, 0. , 0. , 0. , 0.1, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ])

In [8]:
# def f(dofs):
#     cfc.x = dofs
#     return cfc.gamma().copy()

# def df(dofs):
#     cfc.x = dofs
#     return cfc.dgamma_by_dcoeff().copy()
# taylor_test(f, df, coeffs)

# def f(dofs):
#     cfc.x = dofs
#     return cfc.gammadash().copy()

# def df(dofs):
#     cfc.x = dofs
#     return cfc.dgammadash_by_dcoeff().copy()
# taylor_test(f, df, coeffs)

def f(dofs):
    cfc.x = dofs
    return cfc.gammadashdash().copy()

def df(dofs):
    cfc.x = dofs
    return cfc.dgammadashdash_by_dcoeff().copy()
taylor_test(f, df, x)

# def f(dofs):
#     cfc.x = dofs
#     return cfc.gammadashdashdash().copy()

# def df(dofs):
#     cfc.x = dofs
#     return cfc.dgammadashdashdash_by_dcoeff().copy()
# taylor_test(f, df, coeffs)

################################################################################
0.0773321012684462 7.73321012684462e-11
0.019333332922948802 0.2500039777250612
0.0048333524564758545 0.2500009944347791
0.0012083393147659818 0.2500002484087451
0.00030208490746142034 0.25000006518858064
7.552123292092953e-05 0.2500000200459351
1.8880317007361546e-05 0.2500001162206816
4.720072174489882e-06 0.2499996251466275
1.1800196805266065e-06 0.25000034679642075
################################################################################


In [9]:
# taylor_test(f, df, x)

In [10]:
def f(dofs):
            cfc.x = dofs
            return cfc.kappa().copy()

def df(dofs):
    cfc.x = dofs
    return cfc.dkappa_by_dcoeff().copy()

taylor_test(f, df, coeffs)

################################################################################
44.47314126955532 4.447314126955532e-08
44.517239251704694 1.0009915643665037


AssertionError: 